### ISSUE TITLE
String '20210108 00:33:58' was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by Hahahaooovvv** [huanent/Huanent.Logging#4]
![image](https://user-images.githubusercontent.com/33216615/103918096-54142180-5149-11eb-9966-b4c74f49146b.png)
大佬  在线查看日志的在转换时间的时候出错了
```
System.FormatException
  HResult=0x80131537
  Message=String '20210108 00:33:58' was not recognized as a valid DateTime.
  Source=System.Private.CoreLib
  StackTrace:
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.Convert.ToDateTime(String value)
   at Huanent.Logging.File.UI.Areas.Logging.Pages.LogDetailModel.<>c__DisplayClass8_0.<OnGet>b__0(String item) in H:\C#\NetCoreApi\Huanent.Logging.File.UI\Areas\Logging\Pages\LogDetail.cshtml.cs:line 47
   at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)

```
上面是错误信息  
把`.\Huanent.Logging.File.UI\Areas\Logging\Pages\LogDetail.cshtml.cs`中的
```if (lines.Length > 0) log.Time = Convert.ToDateTime(lines[0].Replace("-", ""));```
改成  
```if (lines.Length > 0) log.Time = Convert.ToDateTime(lines[0].Replace("-----", ""));```
就可以了

**Comment by huanent** [comment]
感谢反馈！已修复为
```
if (lines.Length > 0) log.Time = Convert.ToDateTime(lines[0].Trim('-', ' '));
```
nuget包也发了新版的1.1.3

**Comment by Hahahaooovvv** [comment]
棒啊
